### ISSUE TITLE
Default Extension

### ISSUE THREAD

**Issue by mjknght** [facelessuser/FuzzyFileNav#33]
Hi there! A feature I'd like to see is support for a default extension for Fuzzy Make File. Is that something that could be easily done?

**Comment by facelessuser** [comment]
I realize this issue is years old. I planned to get to this much earlier, but life gets in the way. Anyways, as far as a default extension, I don't think it makes sense as you must enter a file name and then execute the command. That requires you to enter the full file name. This doesn't appear to be something we will be adding.
